// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCKtyPQKrNHWROu_TTqciNa96Woc9PZc',
    appId: '1:1090780960469:web:97196405b046fd6598345c',
    messagingSenderId: '1090780960469',
    projectId: 'dday-ecaf3',
    authDomain: 'dday-ecaf3.firebaseapp.com',
    storageBucket: 'dday-ecaf3.firebasestorage.app',
    measurementId: 'G-41EVY9P2N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wCpKW9O6kjEIrcbPqrQ7Pn7hMUFpIQw',
    appId: '1:1090780960469:android:a334436868b27bba98345c',
    messagingSenderId: '1090780960469',
    projectId: 'dday-ecaf3',
    storageBucket: 'dday-ecaf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXMQ1F40HJoV1yTl6nLLEflhN9vSbdTk',
    appId: '1:1090780960469:ios:8d25408f87b8ddf698345c',
    messagingSenderId: '1090780960469',
    projectId: 'dday-ecaf3',
    storageBucket: 'dday-ecaf3.firebasestorage.app',
    iosBundleId: 'com.maxp.doomsDay',
  );
}
